# Generated by Django 5.2.15 on 2026-07-06 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('multimeter', 'Multimeter'), ('oscilloscope', 'Oscilloscope'), ('power_supply', 'Power Supply'), ('function_generator', 'Function Generator'), ('microcontroller', 'Microcontroller'), ('sensor', 'Sensor'), ('other', 'Other')], default='other', max_length=30)),
                ('interface', models.CharField(choices=[('usb', 'USB'), ('serial', 'Serial'), ('lan', 'LAN'), ('gpib', 'GPIB'), ('mqtt', 'MQTT'), ('other', 'Other')], default='usb', max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, help_text='Bench, rack or room location', max_length=100)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('busy', 'Busy'), ('error', 'Error')], default='offline', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['manufacturer', 'model'],
            },
        ),
    ]
