# Generated by Django 5.2.15 on 2026-07-06 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrument',
            options={'ordering': ['manufacturer', 'model'], 'verbose_name': 'Instrument', 'verbose_name_plural': 'Instruments'},
        ),
    ]
