# Generated by Django 5.2.15 on 2026-07-08 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0002_alter_instrument_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='last_connected',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='last_identification',
            field=models.TextField(blank=True),
        ),
    ]
