# Generated by Django 5.2.15 on 2026-07-09 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0003_instrument_last_connected_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrument',
            options={},
        ),
        migrations.AddField(
            model_name='instrument',
            name='driver',
            field=models.CharField(default='mock', help_text='Registered driver name', max_length=50),
        ),
    ]
