# Generated by Django 5.2.15 on 2026-07-10 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0004_alter_instrument_options_instrument_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='connection_timeout',
            field=models.PositiveIntegerField(default=5, help_text='Connection timeout in seconds'),
        ),
    ]
