# Generated by Django 5.2.15 on 2026-07-07 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instruments', '0002_alter_instrument_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('function', models.CharField(max_length=50)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='instruments.instrument')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
